"""Protocol Sanitizer for LLM Chat Message Sequences.

Ensures strict compliance with OpenAI / llama.cpp / Ollama chat completion specifications:
- Cleans orphaned `tool_calls` from assistant messages when corresponding `tool` responses are pruned.
- Prevents 400 Bad Request protocol validation errors.
- Provides lightweight, fast token estimation without heavy external dependencies.
"""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional, Set


def estimate_tokens_rough(text: str) -> int:
    """Heuristic token counter (~3.8 characters per token across English, code, and CJK)."""
    if not text:
        return 0
    # CJK characters typically count as ~1-2 tokens per char in modern tokenizers
    # ASCII text averages ~4 characters per token
    cjk_count = sum(1 for ch in text if '\u4e00' <= ch <= '\u9fff')
    ascii_count = len(text) - cjk_count
    return int((ascii_count / 4.0) + (cjk_count * 1.2)) + 1


def estimate_messages_tokens(messages: List[Dict[str, Any]]) -> int:
    """Estimate total tokens across a list of message dicts."""
    total = 0
    for m in messages:
        content = m.get("content") or ""
        if isinstance(content, str):
            total += estimate_tokens_rough(content)
        elif isinstance(content, list):
            for part in content:
                if isinstance(part, dict) and "text" in part:
                    total += estimate_tokens_rough(part["text"])
        
        # Count tool calls if present
        tool_calls = m.get("tool_calls")
        if tool_calls and isinstance(tool_calls, list):
            for tc in tool_calls:
                if isinstance(tc, dict):
                    fn = tc.get("function", {})
                    total += estimate_tokens_rough(fn.get("name", ""))
                    total += estimate_tokens_rough(fn.get("arguments", ""))
        total += 4  # Per-message formatting overhead
    return total + 2


def sanitize_message_sequence(messages: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    """Sanitize message array to eliminate protocol violations.

    Specifically:
    1. Collects all valid `tool_call_id`s in `role: tool` messages.
    2. Strips any `tool_calls` in assistant messages whose IDs no longer exist in the sequence.
    3. Strips any orphaned `role: tool` messages whose `tool_call_id` does not match any upstream assistant message.
    4. Drops empty content assistant messages that had their tool_calls stripped.
    """
    return ProtocolSanitizer.clean_and_validate(messages)


class ProtocolSanitizer:
    """Production-grade LLM message protocol sanitizer.

    Guarantees strict compliance with OpenAI / llama.cpp / Ollama specifications:
    - Eliminates orphaned tool_calls (assistant has tool_calls but tool output was pruned).
    - Eliminates orphaned tool responses (tool message exists without preceding assistant tool_call).
    - Enforces valid role types ('system', 'user', 'assistant', 'tool').
    - Fixes role alternation and drops empty ghost messages.
    """

    VALID_ROLES = {"system", "user", "assistant", "tool"}

    @classmethod
    def clean_orphaned_tool_calls(cls, messages: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Clean orphaned tool_calls and orphaned tool messages."""
        # 1. Collect all tool_call_ids generated by assistant messages
        assistant_tool_ids: Set[str] = set()
        for m in messages:
            if m.get("role") == "assistant" and "tool_calls" in m:
                tcs = m["tool_calls"]
                if isinstance(tcs, list):
                    for tc in tcs:
                        if isinstance(tc, dict) and tc.get("id"):
                            assistant_tool_ids.add(tc["id"])

        # 2. Collect all tool_call_ids actually answered by tool messages
        answered_tool_ids: Set[str] = {
            m.get("tool_call_id")
            for m in messages
            if m.get("role") == "tool" and m.get("tool_call_id")
        }

        # Mutual intersection: only tool_calls that are both requested AND answered are valid
        valid_tool_ids = assistant_tool_ids & answered_tool_ids

        sanitized: List[Dict[str, Any]] = []
        for m in messages:
            msg = dict(m)
            role = msg.get("role")

            if role == "tool":
                # Drop orphaned tool messages whose caller ID no longer exists
                if msg.get("tool_call_id") not in valid_tool_ids:
                    continue

            elif role == "assistant" and "tool_calls" in msg:
                tcs = msg["tool_calls"]
                if isinstance(tcs, list):
                    # Filter down to only tool_calls that still have a matching tool response
                    matching_tcs = [
                        tc for tc in tcs
                        if isinstance(tc, dict) and tc.get("id") in valid_tool_ids
                    ]
                    if matching_tcs:
                        msg["tool_calls"] = matching_tcs
                    else:
                        msg.pop("tool_calls", None)

                # If tool_calls was removed and content is empty, skip to prevent 400 Bad Request
                if "tool_calls" not in msg and not msg.get("content"):
                    continue

            sanitized.append(msg)

        return sanitized

    MUTATIVE_KEYWORDS = ("write", "edit", "replace", "create", "delete", "patch", "bash", "command", "exec", "terminal", "run", "apply", "migrate")
    READONLY_KEYWORDS = ("read", "view", "get", "list", "grep", "find", "search", "cat", "ls", "check", "inspect")

    @classmethod
    def stub_pruned_tools(
        cls,
        messages: List[Dict[str, Any]],
        *,
        min_chars_to_stub: int = 400,
        protect_tail_tools: int = 2,
    ) -> List[Dict[str, Any]]:
        """Preserve tool execution intent by replacing historical tool outputs with classified stubs.

        Distinguishes:
        - Mutative tools (file edit, command execution): Stubs preserve execution record so model does NOT retry.
        - Read-only tools (read_file, grep): Stubs fold inspection noise.
        - Wording strictly uses 'Result recorded' (never claims 'verified' to avoid false self-endorsement).
        """
        # Map tool_call_id to function name
        call_id_to_fn: Dict[str, str] = {}
        for m in messages:
            if m.get("role") == "assistant" and m.get("tool_calls"):
                for tc in m["tool_calls"]:
                    if isinstance(tc, dict) and tc.get("id"):
                        fn_name = tc.get("function", {}).get("name", "tool")
                        call_id_to_fn[tc["id"]] = fn_name.lower()

        tool_indices = [i for i, m in enumerate(messages) if m.get("role") == "tool"]
        if protect_tail_tools > 0:
            protected_indices = set(tool_indices[-protect_tail_tools:])
        else:
            protected_indices = set()

        stubbed_messages: List[Dict[str, Any]] = []
        for idx, m in enumerate(messages):
            msg = dict(m)
            if msg.get("role") == "tool" and idx not in protected_indices:
                content = msg.get("content")
                if isinstance(content, str) and len(content) > min_chars_to_stub:
                    call_id = msg.get("tool_call_id", "")
                    fn_name = call_id_to_fn.get(call_id, "tool")

                    # Check if mutative vs read-only
                    is_mutative = any(kw in fn_name for kw in cls.MUTATIVE_KEYWORDS)
                    lines = content.strip().splitlines()
                    preview = lines[0][:70] if lines else ""

                    if is_mutative:
                        msg["content"] = (
                            f"[System: Action '{fn_name}' executed. Result recorded ({len(content):,} chars). "
                            f"DO NOT repeat execution. Full output archived to disk. Preview: {preview}...]"
                        )
                    else:
                        msg["content"] = (
                            f"[System: Read-only query '{fn_name}' completed. Result recorded in archive ({len(content):,} chars). "
                            f"Preview: {preview}...]"
                        )
            stubbed_messages.append(msg)

        return stubbed_messages



    @classmethod
    def validate_sequence(cls, messages: List[Dict[str, Any]]) -> List[str]:
        """Validate sequence against OpenAI chat completion specifications.

        Returns a list of warning/error descriptions. An empty list means 100% compliant.
        """
        issues: List[str] = []
        pending_tool_ids: Set[str] = set()
        last_assistant_index: Optional[int] = None

        for idx, m in enumerate(messages):
            role = m.get("role")
            if role not in cls.VALID_ROLES:
                issues.append(f"Message index {idx} has invalid role '{role}'")

            if role == "assistant":
                # If there were previously pending tool calls not answered, flag violation
                if pending_tool_ids:
                    issues.append(
                        f"Assistant at index {idx} intervened before tool responses for ids {sorted(pending_tool_ids)} at index {last_assistant_index}"
                    )
                    pending_tool_ids.clear()

                tcs = m.get("tool_calls")
                if tcs and isinstance(tcs, list):
                    last_assistant_index = idx
                    for tc in tcs:
                        if isinstance(tc, dict) and tc.get("id"):
                            pending_tool_ids.add(tc["id"])

            elif role == "tool":
                tc_id = m.get("tool_call_id")
                if not tc_id:
                    issues.append(f"Tool message at index {idx} missing 'tool_call_id'")
                elif tc_id not in pending_tool_ids:
                    issues.append(f"Tool message at index {idx} has orphaned or unexpected tool_call_id '{tc_id}'")
                else:
                    pending_tool_ids.remove(tc_id)

            elif role in ("user", "system"):
                # If a user/system message comes while tool calls are still pending, violation!
                if pending_tool_ids:
                    issues.append(
                        f"Message '{role}' at index {idx} interrupted pending tool_calls {sorted(pending_tool_ids)} from assistant at index {last_assistant_index}"
                    )
                    pending_tool_ids.clear()

        # Trailing pending tool calls without responses
        if pending_tool_ids:
            issues.append(
                f"Assistant at index {last_assistant_index} has dangling unanswered tool_calls: {sorted(pending_tool_ids)}"
            )

        return issues

    @classmethod
    def clean_and_validate(cls, messages: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
        """Sanitize message array, strip dangling calls, and enforce protocol compliance."""
        if not messages:
            return []

        # 1. Clean orphaned tool_calls and tool messages
        cleaned = cls.clean_orphaned_tool_calls(messages)

        # 2. Guarantee system message placement and remove consecutive identical system prompts
        final_msgs: List[Dict[str, Any]] = []
        seen_system_content: Set[str] = set()

        for m in cleaned:
            role = m.get("role", "user")
            content = m.get("content")

            if role == "system":
                # Deduplicate identical system prompts
                if isinstance(content, str) and content in seen_system_content:
                    continue
                if isinstance(content, str):
                    seen_system_content.add(content)

            final_msgs.append(m)

        return final_msgs

